# Generated by Django 5.0.6 on 2024-07-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_cart_total_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
